### ISSUE TITLE
Confusing names

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#94] opened 2015-07-25 19:34 UTC
The following names need to be changed to make synapter output easier to understand:

Function
Function.1
Function.2

**Comment by sgibb** [comment] 2015-07-25 20:32
Which name(s) do you suggest?

`matchedEMRTs`
`matchedEMRTs.beforeFilterUniqueMatches`
`matchedEMRTs.beforeFilterNonUniqueMatches`

**Comment by sgibb** [comment] 2015-07-25 20:41
duplicate of #67

**Closed by sgibb** 2015-07-25 20:41 UTC
Labels: Important, TODO
